[package]
name = "api"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
log = "0.4.26"
reqwest = { version = "0.12.15", features = ["json"] }
rocket = { version = "0.5.1", features = ["json"] }
tokio = "1"
